smartrecycle/aplicaciones/blogs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView
app_name = 'blogs'

urlpatterns = [
    path('foro/', views.home_page, name='foro'),
    path('post/<slug:slug>', views.PostView.as_view(), name='post'),
    path('featured/', views.FeaturedListView.as_view(), name='featured'),
    path('category/<slug:slug>', views.CategoryListView.as_view(), name='category'),
    path('search/', views.SearchResultsView.as_view(), name='search'),   
]

smartrecycle/smartrecycle/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import inicio, resumen
from django.urls import re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", inicio),
    path("inicio/", inicio, name="inicio"),
    path("", include('aplicaciones.recycle_tips.urls')),
    path("", include('aplicaciones.ubicaciones.urls')),
    path("", include('aplicaciones.blogs.urls')),
    path("", include('aplicaciones.reportes.urls')),
    path("", include('aplicaciones.users.urls')),
    path("", include('aplicaciones.calculadora_huella.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartrecycle/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %} {% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
        {% include "layouts/navbar.html" %}
        {% block content %}  {% endblock %}
    </main>
    <!-- Footer-->
    <!-- {% include "includes/footer.html" %} -->
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

smartrecycle/templates/layouts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Smart<span class="text-gradient">Recycle</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'inicio' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'Mapas' %}">Puntos de Información</a></li>            
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'tips' %}">Tips</a></li>            
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'blogs:foro' %}">Foro</a></li>            
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'blogs:featured' %}">Destacados</a></li>
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'cuestionario_inicio' %}">Huella</a></li>

                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle subtext-style" href="#" role="button" data-bs-toggle="dropdown"aria-expanded="false">Categorías</a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                        <li><a class="dropdown-item" href="{% url 'blogs:category' category.slug %}">{{ category.title}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link subtext-style" href="{% url 'reporte' %}"><img style="width: 30px;" src="https://cdn-icons-png.flaticon.com/512/4201/4201973.png"></a></li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'blogs:search' %}" method="get">
                <input name="search" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" pattern=".*[a-zA-Z0-9].*" title="Debe ingresar al menos una letra o número" required>
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            <ul></ul>
            {% if user.is_authenticated %}
            <form class="d-inline" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary ms-2">Cerrar sesión</button>
            </form>
            {% else %}
            <a class="btn btn-outline-primary ms-2" href="{% url 'login' %}" role="button">Iniciar sesión</a>
            {% endif %}
        </div>
    </div>
</nav>