smartrecycle/aplicaciones/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView
from .views import UserRegistration, AccountVerification
app_name = 'users'

from .views import LoginView
urlpatterns = [
    #Registration
    path('registration/', views.UserRegistration.as_view(), name='registration'),
    path('success/',TemplateView.as_view(template_name='users/success_registration.html'), name='success'),    
    path('register/', UserRegistration.as_view(), name='register'),
    path('verify/<uidb64>/<token>/', AccountVerification.as_view(), name='account_verification'),
    path('login/', LoginView.as_view(), name='login'),   
]

smartrecycle/smartrecycle/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import inicio, resumen
from django.urls import re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", inicio),
    path("inicio/", inicio, name="inicio"),
    path("", include('aplicaciones.recycle_tips.urls')),
    path("", include('aplicaciones.ubicaciones.urls')),
    path("", include('aplicaciones.blogs.urls')),
    path("", include('aplicaciones.reportes.urls')),
    path("", include('aplicaciones.users.urls')),
    path("", include('aplicaciones.calculadora_huella.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartrecycle/aplicaciones/users/models.py
from django.db import models

# Create your models here.

smartrecycle/aplicaciones/users/views.py
from django.shortcuts import render
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import default_token_generator
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from ..blogs.forms import RegisterForm
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import get_user_model
from django.views import View    
from django.utils.encoding import force_str
from django.shortcuts import redirect
from .token import account_activation_token
from django.contrib.auth.views import LoginView as AuthLoginView
UserModel = get_user_model()


class UserRegistration(FormView):
    template_name = 'users/registration.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:success')#blogs:success
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False  # Deactivate account till it is confirmed
        user.save()

        current_site = get_current_site(self.request)
        mail_subject = 'Activate your account.'
        message = render_to_string('users/acc_active_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': default_token_generator.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(mail_subject, message, to=[to_email])
        if email.send():
            messages.success(self.request, f'Estimado/a {user}, vaya a la bandeja de entrada de su correo electrónico {to_email} y haga clic en \
                el enlace de activación recibido para confirmar y completar el registro. Nota: revisa tu carpeta de spam.')
        else:
            messages.error(self.request, f'Problem sending email to {to_email}, check if you typed it correctly.')

        return super(UserRegistration, self).form_valid(form)
class AccountVerification(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = UserModel.objects.get(pk=uid)
            if default_token_generator.check_token(user, token):
                user.is_active = True
                user.save()
                messages.success(request, 'Tu cuenta ha sido activada exitosamente, ahora puedes iniciar sesión', extra_tags='activacion_cuenta')
                return redirect('login')
            else:
                messages.error(request, 'El enlace de activación es inválido', extra_tags='error_activacion')
                return redirect('login')
        except(TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
            messages.error(request, 'El enlace de activación es inválido', extra_tags='error_activacion')
            return redirect('login')    
class LoginView(AuthLoginView):
    def get(self, request, *args, **kwargs):
        message = request.session.pop('account_activation_message', None)
        if message:
            messages.success(request, message)
        return super().get(request, *args, **kwargs)      

smartrecycle/aplicaciones/users/templates/users/acc_active_email.html
Hola {{ user.username }}
Gracias por registrarte en nuestro sitio web. Por favor, haz clic en el enlace de abajo para verificar tu cuenta:
http://{{ domain }}{% url 'users:account_verification' uidb64=uid token=token %}"
Si no te has registrado en nuestro sitio web, por favor, ignora este correo electrónico.

smartrecycle/aplicaciones/users/templates/users/registration.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-3"></div>

            <div class="col-md-6">

                <div class="w-100 m-auto text-center">
                    <!-- Aquí es donde se mostrarán los mensajes -->
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    

                    <form method="POST" class="form-group">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Register</button>
                    </form>
                </div>
            </div>

            <div class="col-md-3"></div>
        </div>

    </main>
</div>
{% endblock %}

smartrecycle/aplicaciones/users/templates/users/success_registration.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
            <div class="col-md-3"></div>

            <div class="col-md-6">

                <div class="w-100 m-auto text-center">
                    
                    <h1>Registro Exitoso</h1>

                    <!-- Agrega esto donde quieras que se muestren los mensajes -->
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}

                    <a class="btn btn-outline-primary mb-5" href="{% url 'login' %}" role="button">Sign In</a>
                </div>
            </div>

            <div class="col-md-3"></div>
        </div>

    </main>
</div>
{% endblock %}